#!/bin/bash
set -e

echo "===> Configuring OpenBMP Environment"
export SYS_NUM_CPU=$(grep processor /proc/cpuinfo | wc -l)

# JVM defaults
export JAVA_XMX=${OPENBMP_JAVA_XMX:-512m}
export JAVA_XMS=${OPENBMP_JAVA_XMS:-512m}
export JAVA_EXTRA_OPTS=${OPENBMP_JAVA_EXTRA_OPTS:-"\
    -XX:+UseG1GC \
    -XX:+UnlockExperimentalVMOptions \
    -XX:InitiatingHeapOccupancyPercent=30 \
    -XX:G1MixedGCLiveThresholdPercent=30 \
    -XX:MaxGCPauseMillis=200 \
    -XX:ParallelGCThreads=20 \
    -XX:ConcGCThreads=5 \
    -XX:+ExitOnOutOfMemoryError \
    -Duser.timezone=UTC"}

export JAVA_OPTS="-Xmx${JAVA_XMX} -Xms${JAVA_XMS} ${JAVA_EXTRA_OPTS}"

# Required for kcat (formerly kafkacat) during validation checks
export OPENBMP_KAFKA_SSL_CERTIFICATE_LOCATION=${OPENBMP_KAFKA_SSL_CERTIFICATE_LOCATION:-}
export OPENBMP_KAFKA_SSL_KEY_LOCATION=${OPENBMP_KAFKA_SSL_KEY_LOCATION:-}
export OPENBMP_KAFKA_SSL_KEY_PASSWORD=${OPENBMP_KAFKA_SSL_KEY_PASSWORD:-}
export OPENBMP_KAFKA_SSL_CA_LOCATION=${OPENBMP_KAFKA_SSL_CA_LOCATION:-}
if [[ "$OPENBMP_KAFKA_SSL_ENABLED" == "true" ]]; then

    # CA certificate is required for SSL at a minimum
    if [[ ! -f $OPENBMP_KAFKA_SSL_CA_LOCATION ]]; then
        echo "ERROR: OPENBMP_KAFKA_SSL_CA_LOCATION file is missing or empty: $OPENBMP_KAFKA_SSL_CA_LOCATION"
        exit 1
    fi
fi

# optional cron services
export OPENBMP_DBIP_ENABLED=${OPENBMP_DBIP_ENABLED:-0}
export OPENBMP_IRR_ENABLED=${OPENBMP_IRR_ENABLED:-0}
export OPENBMP_RPKI_ENABLED=${OPENBMP_RPKI_ENABLED:-0}
export OPENBMP_RPKI_URL=${OPENBMP_RPKI_URL:-https://rpki.cloudflare.com/rpki.json}
export OPENBMP_RPKI_USERNAME=${OPENBMP_RPKI_USERNAME:-None}
export OPENBMP_RPKI_PASSWORD=${OPENBMP_RPKI_PASSWORD:-None}
