#!/bin/bash
set -e

echo "===> Configuring PostgreSQL Shell Profile"
cat <<EOF > /usr/local/openbmp/pg_profile
export PGDATABASE=$OPENBMP_POSTGRES_DB
export PGHOST=$OPENBMP_POSTGRES_HOST
export PGPORT=$OPENBMP_POSTGRES_PORT
export PGUSER=$OPENBMP_POSTGRES_USERNAME
export PGPASSWORD=$OPENBMP_POSTGRES_PASSWORD
EOF
