# OpenBMP Consumer Volumes
# https://docs.docker.com/reference/compose-file/volumes/#example
volumes:
  config:
    name: openbmp-consumer-config
  logs:
    name: openbmp-consumer-logs
  pki:
    name: openbmp-pki
    external: true

# OpenBMP Consumer Services
# https://docs.docker.com/reference/compose-file/services/
services:
  consumer:
    container_name: obmp-consumer
    image: openbmp/psql-app:2.2.2
    restart: unless-stopped

    # Consumer App - Exposed Ports
    # https://docs.docker.com/reference/compose-file/services/#ports
    ports:
      - "9005:9005"

    # Consumer App - Extra sysctls
    # https://docs.docker.com/reference/compose-file/services/#sysctls
    sysctls:
      - net.ipv4.tcp_keepalive_intvl=30
      - net.ipv4.tcp_keepalive_probes=5
      - net.ipv4.tcp_keepalive_time=180

    # Consumer App - Mounts
    # https://docs.docker.com/reference/compose-file/services/#volumes
    volumes:
      - config:/config
      - logs:/var/log
      - pki:/etc/openbmp/pki:ro

    # Consumer App - Extra /etc/hosts entries
    # https://docs.docker.com/reference/compose-file/services/#extra_hosts
    extra_hosts:
      - "patroni1:192.0.2.1"
      - "patroni2:192.0.2.2"
      - "kafka1:192.0.2.1"
      - "kafka2:192.0.2.2"
      - "kafka3:192.0.2.3"

    # Consumer App - Environment Variables
    # https://docs.docker.com/reference/compose-file/services/#environment
    environment:
      # Optional services
      OPENBMP_IRR_ENABLED: 1
      OPENBMP_DBIP_ENABLED: 1
      OPENBMP_RPKI_ENABLED: 1
      # RPKI validation
      OPENBMP_RPKI_URL: "https://rpki.cloudflare.com/rpki.json"
      OPENBMP_RPKI_PASS: None
      OPENBMP_RPKI_USER: None
      # Consumer App JVM options
      OPENBMP_JAVA_XMX: 1g
      OPENBMP_JAVA_XMS: 1g
      OPENBMP_JAVA_EXTRA_OPTS: >-
        -XX:+UseG1GC
        -XX:+UnlockExperimentalVMOptions
        -XX:InitiatingHeapOccupancyPercent=30
        -XX:G1MixedGCLiveThresholdPercent=30
        -XX:MaxGCPauseMillis=200
        -XX:ParallelGCThreads=20
        -XX:ConcGCThreads=5
        -XX:+ExitOnOutOfMemoryError
        -Duser.timezone=UTC
      # PostgreSQL client options
      OPENBMP_POSTGRES_DB: openbmp
      OPENBMP_POSTGRES_HOST: patroni1
      OPENBMP_POSTGRES_PORT: 5432
      OPENBMP_POSTGRES_USERNAME: openbmp
      OPENBMP_POSTGRES_PASSWORD: openbmp
      # TODO: PostgesSQL mTLS options
      OPENBMP_POSTGRES_SSL_ENABLED: true
      OPENBMP_POSTGRES_SSL_MODE: require
      # Kafka client options
      OPENBMP_KAFKA_BROKERS: "kafka1:9092,kafka2:9092"
      OPENBMP_KAFKA_SSL_ENABLED: true
      OPENBMP_KAFKA_SSL_KEYSTORE_PASSWORD: openbmp
      OPENBMP_KAFKA_SSL_TRUSTSTORE_PASSWORD: openbmp
      OPENBMP_KAFKA_SSL_KEYSTORE_LOCATION: "/etc/openbmp/pki/openbmp_keystore.jks"
      OPENBMP_KAFKA_SSL_TRUSTSTORE_LOCATION: "/etc/openbmp/pki/openbmp_truststore.jks"
      OPENBMP_KAFKA_SSL_CERTIFICATE_LOCATION: "/etc/openbmp/pki/openbmp.pem"
      OPENBMP_KAFKA_SSL_KEY_LOCATION: "/etc/openbmp/pki/openbmp.key"
      OPENBMP_KAFKA_SSL_CA_LOCATION: "/etc/openbmp/pki/openbmp_ca.pem"