/var/log/messages {
    daily
    rotate 14
    compress
    missingok
    notifempty
    copytruncate
    dateext
    create 0644 root root
}

/var/log/*.log {
    daily
    rotate 14
    compress
    missingok
    notifempty
    copytruncate
    dateext
    create 0644 root root
}

/var/log/openbmp/*.log {
    daily
    rotate 30
    compress
    missingok
    notifempty
    copytruncate
    dateext
    create 0644 root root
}

# Ignore supervisord logs
/var/log/supervisor/* {
    missingok
    notifempty
    # supervisord manages these logs
    nocreate
    nodateext
    rotate 0
}