[supervisord]
user=root
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=info
logformat=%(asctime)s [%(processName)s] %(message)s

[program:rsyslogd]
command=/usr/sbin/rsyslogd -n
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/rsyslog.err.log
stdout_logfile=/var/log/supervisor/rsyslog.out.log
stderr_logfile_maxbytes=1MB
stdout_logfile_maxbytes=1MB
stderr_logfile_backups=3
stdout_logfile_backups=3

[program:crond]
command=/usr/sbin/crond -f
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/crond.err.log
stdout_logfile=/var/log/supervisor/crond.out.log
stderr_logfile_maxbytes=1MB
stdout_logfile_maxbytes=1MB
stderr_logfile_backups=3
stdout_logfile_backups=3

[program:consumer]
directory=/var/log/openbmp
command=java %(ENV_JAVA_OPTS)s -jar /usr/local/openbmp/obmp-psql-consumer.jar -cf /config/obmp-psql.yml
autorestart=true
stderr_logfile=/var/log/supervisor/consumer.err.log
stdout_logfile=/var/log/supervisor/consumer.out.log
stderr_logfile_maxbytes=1MB
stdout_logfile_maxbytes=1MB
stderr_logfile_backups=3
stdout_logfile_backups=3
log_stdout=true
log_stderr=true

